/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.GUI;

import com.Comparators.ByCategory;
import com.Comparators.ByName;
import com.Comparators.ByShop;
import com.Persistance.RecordSeeker;
import com.Product;
import com.ShoppingList;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

/**
 * @author grobles
 */
public class MainForm extends javax.swing.JFrame {
    private EditProduct editProduct;
    private EditCategory editCategory;
    private EditShop editShop;
    private List<Product> arrayShoppingProduct;
    private RecordSeeker recordSeeker;
    public JComboBox jComboBoxCategory;
    public JComboBox jComboBoxProduct;


    /**
     * Creates new form NewJFrame
     */
    public MainForm() {
        recordSeeker = new RecordSeeker();
        recordSeeker.writToXml();
        String[] comboCategory = recordSeeker.setStringArray(recordSeeker.getcategoryList());
        arrayShoppingProduct = new ArrayList<Product>();
        initComponents();
        jComboBoxCategory.setModel(new DefaultComboBoxModel(comboCategory));
        setComboProduct();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBoxProduct = new javax.swing.JComboBox();
        jComboBoxCategory = new javax.swing.JComboBox();
        jLabelProduct = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSortAZ = new javax.swing.JButton();
        jButtonCategry = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonSortShop = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableShoppingProducts = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSendEmail = new javax.swing.JMenuItem();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemEdtProduct = new javax.swing.JMenuItem();
        jMenuItemEditCategory = new javax.swing.JMenuItem();
        jMenuItemEditShop = new javax.swing.JMenuItem();
        jMenuLists = new javax.swing.JMenu();
        jMenuItemListProducts = new javax.swing.JMenuItem();
        jMenuItemListCategories = new javax.swing.JMenuItem();
        jMenuItemListShops = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping List App");


        jLabelProduct.setText("Product");

        jLabelCategory.setText("Category");


        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSortAZ.setText("Sort A_Z");
        jButtonSortAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortAZActionPerformed(evt);
            }
        });

        jButtonCategry.setText("Sort Category");
        jButtonCategry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategryActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonSortShop.setText("Sort Shop");
        jButtonSortShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortShopActionPerformed(evt);
            }
        });

        jTableShoppingProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
                }
        ));
        jScrollPane3.setViewportView(jTableShoppingProducts);

        jMenuFile.setText("File");

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuItemSendEmail.setText("Send By Email");
        jMenuItemSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSendEmailActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSendEmail);

        jMenuItemPrint.setText("Print");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemPrint);

        jMenuItemClose.setText("Close");
        jMenuFile.add(jMenuItemClose);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemEdtProduct.setText("Edit/Add Product");
        jMenuItemEdtProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdtProductActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEdtProduct);

        jMenuItemEditCategory.setText("Edit/Add Category");
        jMenuItemEditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditCategoryActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEditCategory);

        jMenuItemEditShop.setText("Edit/Add Shop");
        jMenuItemEditShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditShopActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEditShop);

        jMenuBar.add(jMenuEdit);

        jMenuLists.setText("Lists");

        jMenuItemListProducts.setText("Products");
        jMenuItemListProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListProductsActionPerformed(evt);
            }
        });
        jMenuLists.add(jMenuItemListProducts);

        jMenuItemListCategories.setText("Categories");
        jMenuItemListCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListCategoriesActionPerformed(evt);
            }
        });
        jMenuLists.add(jMenuItemListCategories);

        jMenuItemListShops.setText("Shops");
        jMenuItemListShops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListShopsActionPerformed(evt);
            }
        });
        jMenuLists.add(jMenuItemListShops);

        jMenuBar.add(jMenuLists);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonDelete)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonClear))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(jLabelCategory))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSortAZ, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonCategry)
                                                .addGap(35, 35, 35)
                                                .addComponent(jButtonSortShop, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCategory)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabelProduct)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonAdd)
                                                        .addComponent(jButtonDelete)
                                                        .addComponent(jButtonClear))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonSortAZ)
                                                        .addComponent(jButtonCategry)
                                                        .addComponent(jButtonSortShop)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if (arrayShoppingProduct.size() > 1) {
            String name =
                    JOptionPane.showInputDialog("Enter the name for the Shopping List");


            ShoppingList List = new ShoppingList(name, arrayShoppingProduct);
            recordSeeker.getShoppingList().add(List);
            recordSeeker.writToXml();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "You have to add products to the list");
        }
    }

    private void jButtonSortAZActionPerformed(java.awt.event.ActionEvent evt) {
        Collections.sort(arrayShoppingProduct, new ByName());
        setTable();

    }

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemSendEmailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {
        this.setComboProduct();
    }


    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Product product = (Product) recordSeeker.findItem(jComboBoxProduct.getSelectedItem().toString(), "Product");
            arrayShoppingProduct.add(product);
            setTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), "You have to choose a Product");
        }
    }


    private void setTable() {
        jTableShoppingProducts.setModel((new javax.swing.table.DefaultTableModel(
                setStringShoppingPanel(arrayShoppingProduct),
                new String[]{
                        "Product", "Category", "Shop", "Quantity", "Unit"
                })));
    }


    private String[][] setStringShoppingPanel(List arraylist) {
        int size = arraylist.size();
        String StringArray[][] = new String[size][5];
        int i = 0;
        Iterator iterator = arraylist.iterator();
        while (iterator.hasNext()) {
            for (int row = 0; row < arrayShoppingProduct.size(); row++) {
                Product product = (Product) iterator.next();
                StringArray[row][0] = product.getItemName();
                StringArray[row][1] = product.getItemCategory().getItemName();
                StringArray[row][2] = product.getItemShop().getItemName();
                StringArray[row][3] = Integer.toString(product.getItemQuantity());
                StringArray[row][4] = product.getItemUnit();
            }
        }
        return StringArray;
    }


    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int row = jTableShoppingProducts.getSelectedRow();
            Product product = arrayShoppingProduct.get(row);
            arrayShoppingProduct.remove(product);
            setTable();
        } catch (Exception ex) {

        }
    }

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {
        arrayShoppingProduct = new ArrayList<Product>();
        setTable();
    }

    private void jButtonCategryActionPerformed(java.awt.event.ActionEvent evt) {
        Collections.sort(arrayShoppingProduct, new ByCategory());
        setTable();
    }

    private void jButtonSortShopActionPerformed(java.awt.event.ActionEvent evt) {
        Collections.sort(arrayShoppingProduct, new ByShop());
        setTable();
    }

    private void jMenuItemEdtProductActionPerformed(java.awt.event.ActionEvent evt) {
        if (editProduct == null) {
            editProduct = new EditProduct(this);
            editProduct.setVisible(true);
        } else {
            editProduct.setVisible(true);

        }
    }

    private void jMenuItemEditCategoryActionPerformed(java.awt.event.ActionEvent evt) {
        if (editCategory == null) {
            editCategory = new EditCategory(this);
            editCategory.setVisible(true);
        } else {
            editCategory.setVisible(true);

        }
    }

    private void jMenuItemEditShopActionPerformed(java.awt.event.ActionEvent evt) {
        if (editShop == null) {
            editShop = new EditShop(this);
            editShop.setVisible(true);
        } else {
            editShop.setVisible(true);

        }
    }

    private void jMenuItemListProductsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemListCategoriesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemListShopsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    void setComboProduct() {
        String categoryName = new String();
        try {
            categoryName = jComboBoxCategory.getSelectedItem().toString();
        } catch (Exception ex) {

        }
        List<Product> productList = (List<Product>) recordSeeker.getProductList();
        List<Product> list = new ArrayList<Product>();
        for (Product product : productList) {
            if (product.getItemCategory().getItemName().equals(categoryName)) {
                list.add(product);
            }
        }

        jComboBoxProduct.setModel(new javax.swing.DefaultComboBoxModel(recordSeeker.setStringArray(list)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCategry;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSortAZ;
    private javax.swing.JButton jButtonSortShop;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemEditCategory;
    private javax.swing.JMenuItem jMenuItemEditShop;
    private javax.swing.JMenuItem jMenuItemEdtProduct;
    private javax.swing.JMenuItem jMenuItemListCategories;
    private javax.swing.JMenuItem jMenuItemListProducts;
    private javax.swing.JMenuItem jMenuItemListShops;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSendEmail;
    private javax.swing.JMenu jMenuLists;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableShoppingProducts;
    // End of variables declaration
}
